"""removed index on DispBase.import hash

Peek Plugin Database Migration Script

Revision ID: 809f1a822abf
Revises: 225ea0bc2ba2
Create Date: 2017-07-06 13:11:37.786851

"""

# revision identifiers, used by Alembic.
revision = '809f1a822abf'
down_revision = '225ea0bc2ba2'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
import geoalchemy2


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_Disp_importHash', table_name='DispBase', schema='pl_diagram')
    op.drop_index('idx_DispEllipse_geom', table_name='DispEllipse', schema='pl_diagram')
    op.drop_index('idx_DispGroupPointer_geom', table_name='DispGroupPointer', schema='pl_diagram')
    op.drop_index('idx_DispPolygon_geom', table_name='DispPolygon', schema='pl_diagram')
    op.drop_index('idx_DispPolyline_geom', table_name='DispPolyline', schema='pl_diagram')
    op.drop_index('idx_DispText_geom', table_name='DispText', schema='pl_diagram')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_DispText_geom', 'DispText', ['geom'], unique=False, schema='pl_diagram')
    op.create_index('idx_DispPolyline_geom', 'DispPolyline', ['geom'], unique=False, schema='pl_diagram')
    op.create_index('idx_DispPolygon_geom', 'DispPolygon', ['geom'], unique=False, schema='pl_diagram')
    op.create_index('idx_DispGroupPointer_geom', 'DispGroupPointer', ['geom'], unique=False, schema='pl_diagram')
    op.create_index('idx_DispEllipse_geom', 'DispEllipse', ['geom'], unique=False, schema='pl_diagram')
    op.create_index('idx_Disp_importHash', 'DispBase', ['importHash'], unique=True, schema='pl_diagram')
    # ### end Alembic commands ###