"""Added BranchIndex

Peek Plugin Database Migration Script

Revision ID: a42f36686d2d
Revises: 5e2f84d757f2
Create Date: 2018-12-30 21:35:03.937306

"""

# revision identifiers, used by Alembic.
revision = 'a42f36686d2d'
down_revision = '5e2f84d757f2'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
import geoalchemy2


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('BranchIndexCompilerQueue',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('modelSetId', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('chunkKey', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['modelSetId'], ['pl_diagram.ModelSet.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', 'chunkKey'),
    schema='pl_diagram'
    )
    op.create_table('BranchIndexEncodedChunk',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('modelSetId', sa.Integer(), nullable=False),
    sa.Column('chunkKey', sa.String(), nullable=False),
    sa.Column('encodedData', sa.LargeBinary(), nullable=False),
    sa.Column('encodedHash', sa.String(), nullable=False),
    sa.Column('lastUpdate', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['modelSetId'], ['pl_diagram.ModelSet.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='pl_diagram'
    )
    op.create_index('idx_BranchIndexEnc_modelSetId_chunkKey', 'BranchIndexEncodedChunk', ['modelSetId', 'chunkKey'], unique=False, schema='pl_diagram')
    op.create_table('BranchIndex',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('coordSetId', sa.Integer(), nullable=False),
    sa.Column('importGroupHash', sa.String(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('chunkKey', sa.String(), nullable=False),
    sa.Column('packedJson', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['coordSetId'], ['pl_diagram.ModelCoordSet.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='pl_diagram'
    )
    op.create_index('idx_BranchIndex_chunkKey', 'BranchIndex', ['chunkKey'], unique=False, schema='pl_diagram')
    op.create_index('idx_BranchIndex_importGroupHash', 'BranchIndex', ['importGroupHash'], unique=False, schema='pl_diagram')
    op.create_index('idx_BranchIndex_key', 'BranchIndex', ['coordSetId', 'key'], unique=True, schema='pl_diagram')
    op.create_table('BranchGridIndex',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('branchIndexId', sa.Integer(), nullable=False),
    sa.Column('gridKey', sa.String(), nullable=False),
    sa.Column('packedJson', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['branchIndexId'], ['pl_diagram.BranchIndex.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='pl_diagram'
    )
    op.create_index('idx_BranchGridIndex_key', 'BranchGridIndex', ['branchIndexId', 'gridKey'], unique=True, schema='pl_diagram')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_BranchGridIndex_key', table_name='BranchGridIndex', schema='pl_diagram')
    op.drop_table('BranchGridIndex', schema='pl_diagram')
    op.drop_index('idx_BranchIndex_key', table_name='BranchIndex', schema='pl_diagram')
    op.drop_index('idx_BranchIndex_importGroupHash', table_name='BranchIndex', schema='pl_diagram')
    op.drop_index('idx_BranchIndex_chunkKey', table_name='BranchIndex', schema='pl_diagram')
    op.drop_table('BranchIndex', schema='pl_diagram')
    op.drop_index('idx_BranchIndexEnc_modelSetId_chunkKey', table_name='BranchIndexEncodedChunk', schema='pl_diagram')
    op.drop_table('BranchIndexEncodedChunk', schema='pl_diagram')
    op.drop_table('BranchIndexCompilerQueue', schema='pl_diagram')
    # ### end Alembic commands ###